services:
  - type: web
    name: mindora-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: build,runtime
      - key: JWT_SECRET
        scope: runtime
      - key: GEMINI_API_KEY
        scope: runtime
      - key: CLIENT_URL
        scope: runtime
      - key: OAUTH_CLIENT_ID
        scope: runtime
      - key: OAUTH_CLIENT_SECRET
        scope: runtime
      - key: OAUTH_CALLBACK_URL
        scope: runtime
      - key: EMAIL_USER
        scope: runtime
      - key: EMAIL_PASS
        scope: runtime
      - key: EMAIL_SERVICE
        scope: runtime
        value: gmail
      - key: GROQ_API_KEY
        scope: runtime
      - key: API_URL
        scope: runtime
      - key: NODE_ENV
        value: production
    autoDeploy: false
    healthCheckPath: /health
